### ISSUE TITLE
Investigate explicit session close

### ISSUE THREAD

**Issue by Theodus** [Theodus/jennet#18]
afaik you don't need to close the session explicitly here. The http_server session is already closing the tcp connection when it receives a `Connection: close` header in the call to `send`.

_Originally posted by @mfelsche in https://github.com/Theodus/jennet/pull/16_

**Comment by mfelsche** [comment]
This is due to a bug in `http_server` only closing the session if the client-request contained a `Connection: close`. This logic needs to be broadened a little bit according to: https://tools.ietf.org/html/rfc7230#section-6.3

**Comment by mfelsche** [comment]
Release 0.2.1 of http_server should fix this and the explicit closings can be removed, once we upgrade.
