### ISSUE TITLE
problem compiling jennet example

### ISSUE THREAD

**Issue by shomodj** [Theodus/jennet#3]
Hi,

not sure if im doing something wrong but I'm trying to compile one of the examples and I get this error:

context.pony:11:7: syntax error: expected name after class
class iso Context
      ^

pony is 0.2.1

thanks

**Comment by Theodus** [comment]
This package is not backwards compatible with the last release version. I'm very sorry for the confusion, I should make a note of that in the README.

**Comment by shomodj** [comment]
Ah, thanks.
